### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by fgeierst** [fgeierst/warumichhierbin#1]
| Performance |  LCP | TBT   | CLS |
| ----------- |  --- | ----- | --- |
| 42          |    5s  | 1,510 ms | 0   |

- [x] remove redirection
- [x] WP Super Cache → Lighthouse Perf went up from 42 to 85
- [x] Reduce font weights, host fonts locally #4 
- [x] redirect from http to https #2 
- [x] Enable text compression on server in .htaccess
- [x] Setup cache policy headers in .htaccess #7 
- [x] preconnect to vimeo.com
- [x] Serve webp / size images responsively #5

**Comment by fgeierst** [comment]
- [x] remove redirection

**Comment by fgeierst** [comment]
- [ ] explore if it's possible to remove one font weight (500)? 
- [ ] serve font [Red+Hat+Text:400,500,700](https://fonts.google.com/specimen/Red+Hat+Text) locally

**Comment by fgeierst** [comment]
- [ ] Serve webp / size images responsively
- [ ] enable text compression on server in .htaccess

**Comment by fgeierst** [comment]
# Ressources
- https://wordpress.org/support/article/optimization/

**Comment by fgeierst** [comment]
| Performance |  LCP | TBT   | CLS |
| ----------- |  --- | ----- | --- |
| 94          |    1.8s  | 170 ms | 0   |
